// <auto-generated />
using System;
using BloodSugarWatchdog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodSugarWatchdog.Data.Migrations
{
    [DbContext(typeof(BloodSugarContext))]
    partial class BloodSugarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.BglDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BglDevices");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.BglDirection", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type");

                    b.ToTable("BglDirections");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.BglEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Delta")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Filtered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Noise")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rssi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sgv")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SysTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unfiltered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtcOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DirectionType");

                    b.ToTable("BglEntries");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.Treatment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Carbs")
                        .HasColumnType("REAL");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Insulin")
                        .HasColumnType("REAL");

                    b.Property<string>("InsulinInjections")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsulinType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SysTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtcOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.TreatmentDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TreatmentDevices");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.BglEntry", b =>
                {
                    b.HasOne("BloodSugarWatchdog.Data.Entities.BglDevice", "Device")
                        .WithMany("Entries")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodSugarWatchdog.Data.Entities.BglDirection", "Direction")
                        .WithMany("Entries")
                        .HasForeignKey("DirectionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.Treatment", b =>
                {
                    b.HasOne("BloodSugarWatchdog.Data.Entities.TreatmentDevice", "Device")
                        .WithMany("Treatments")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.BglDevice", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.BglDirection", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BloodSugarWatchdog.Data.Entities.TreatmentDevice", b =>
                {
                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
